apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-chart.fullname" . }}
  labels:
    app: {{ include "redis-chart.name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "redis-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379
          command: ["redis-server", "--appendonly", "yes"]
