apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-chart.fullname" . }}
  labels:
    app: {{ include "redis-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: {{ include "redis-chart.name" . }}
