# did not use
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
  labels:
    type: mssql-data
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
